Try haskell-ci generated script

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,20 +1,111 @@
-# Based off https://github.com/domenkozar/hie-nix/blob/master/.travis.yml
-language: nix
-sudo: required
-before_script:
-- sudo mount -o remount,exec,size=4G,mode=755 /run/user || true
-env:
-  global:
-  - secure: tf8O2IZiH/cxirKW9yPQ//ZTPBFlA3xMADeKfx7Wm8aNZnKPyNe/pwGnR+lLkqy7QpghhD9ja+ozg79Ks7Ow53mgkEVDvkaaNzEfxVsOwpa6xCdkhmm1AQiS9a81y21DGT2tqHk1FPKOxTCMSjB4Rt+in1lcguYJ70ZstlA4BEyR4+ecxQA3+0ISArwNCAkhSGtxKhPujm6j0D2a49IoNiM9Wtc7M34CjpNjVQ9vars8Lzn7k5KVFlh2jdOswaqMrzywb5pVcY2VWrXogDlHkwp1XUv7KIHs3pJPiwgMJaHPN6WTIB7cCd3ijcw9QPV6lu54dtf00Gg0PeOS7mpIjDzY/wNdbzlgHASVUw8T+5kgrdRAqNTH5RSeObeTMHG3nZW3nIasqEYpGhdtxP80A2/4X5oM7Fn+ffMgwcwEKIPNwRgV0Wb/uBcgwGMEdHsFdRPZrWpH7RHcnbKNCHEW4XFMy5MjuuveaH8B3b5lls9jNMQYIdEaZhvLYQ1XjlKiVSuhy+/MXfpSRKIvLbEc7GnJICRFY0Ke2J2+UZ0+/E1goP83MGbB8n2LPDqtN0kx81m+YY+Jshc95MAkbd35qcb30oWvYWME7cw4gLNLrxC5aBP0EB0FFbf76eeNz8fVJ1KlyCjIZCsP8vdfvtaaciehRxO/81xztauqyHLy/R8=
+# This Travis job script has been generated by a script via
+#
+#   runghc make_travis_yml_2.hs 'cabal.project'
+#
+# For more information, see https://github.com/haskell-CI/haskell-ci
+#
+language: c
+sudo: false
+
+git:
+  submodules: false  # whether to recursively clone submodules
+
+cache:
+  directories:
+    - $HOME/.cabal/packages
+    - $HOME/.cabal/store
+
+before_cache:
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
+  # remove files that are regenerated by 'cabal update'
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.*
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/*.json
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.cache
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar.idx
+
+  - rm -rfv $HOME/.cabal/packages/head.hackage
+
+matrix:
+  include:
+    - compiler: "ghc-8.6.3"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-2.4,ghc-8.6.3], sources: [hvr-ghc]}}
+
+before_install:
+  - HC=${CC}
+  - HCPKG=${HC/ghc/ghc-pkg}
+  - unset CC
+  - ROOTDIR=$(pwd)
+  - mkdir -p $HOME/.local/bin
+  - "PATH=/opt/ghc/bin:/opt/ghc-ppa-tools/bin:$HOME/local/bin:$PATH"
+  - HCNUMVER=$(( $(${HC} --numeric-version|sed -E 's/([0-9]+)\.([0-9]+)\.([0-9]+).*/\1 * 10000 + \2 * 100 + \3/') ))
+  - echo $HCNUMVER
+
+install:
+  - cabal --version
+  - echo "$(${HC} --version) [$(${HC} --print-project-git-commit-id 2> /dev/null || echo '?')]"
+  - BENCH=${BENCH---enable-benchmarks}
+  - TEST=${TEST---enable-tests}
+  - HADDOCK=${HADDOCK-true}
+  - UNCONSTRAINED=${UNCONSTRAINED-true}
+  - NOINSTALLEDCONSTRAINTS=${NOINSTALLEDCONSTRAINTS-false}
+  - GHCHEAD=${GHCHEAD-false}
+  - travis_retry cabal update -v
+  - "sed -i.bak 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config"
+  - rm -fv cabal.project cabal.project.local
+  - grep -Ev -- '^\s*--' ${HOME}/.cabal/config | grep -Ev '^\s*$'
+  - "printf 'packages: \"gi-gtk-declarative\" \"gi-gtk-declarative-app-simple\" \"examples\"\\n' > cabal.project"
+  - "printf 'write-ghc-environment-files: always\\n' >> cabal.project"
+  - touch cabal.project.local
+  - "if ! $NOINSTALLEDCONSTRAINTS; then for pkg in $($HCPKG list --simple-output); do echo $pkg  | grep -vw -- gi-gtk-declarative | grep -vw -- gi-gtk-declarative-app-simple | grep -vw -- examples | sed 's/^/constraints: /' | sed 's/-[^-]*$/ installed/' >> cabal.project.local; done; fi"
+  - cat cabal.project || true
+  - cat cabal.project.local || true
+  - if [ -f "gi-gtk-declarative/configure.ac" ]; then
+      (cd "gi-gtk-declarative" && autoreconf -i);
+    fi
+  - if [ -f "gi-gtk-declarative-app-simple/configure.ac" ]; then
+      (cd "gi-gtk-declarative-app-simple" && autoreconf -i);
+    fi
+  - if [ -f "examples/configure.ac" ]; then
+      (cd "examples" && autoreconf -i);
+    fi
+  - rm -f cabal.project.freeze
+  - cabal new-build -w ${HC} ${TEST} ${BENCH} --project-file="cabal.project" --dep -j2 all
+  - cabal new-build -w ${HC} --disable-tests --disable-benchmarks --project-file="cabal.project" --dep -j2 all
+  - rm -rf .ghc.environment.* "gi-gtk-declarative"/dist "gi-gtk-declarative-app-simple"/dist "examples"/dist
+  - DISTDIR=$(mktemp -d /tmp/dist-test.XXXX)
+
+# Here starts the actual work to be performed for the package under test;
+# any command which exits with a non-zero exit code causes the build to fail.
 script:
-- nix-env -if https://github.com/cachix/cachix/tarball/master --extra-substituters https://cachix.cachix.org --trusted-public-keys 'cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cachix.cachix.org-1:eWNHQldwUO7G2VkjpnjDbWwy4KQ/HNxht7H4SSoMckM='
-- cachix use gi-gtk-declarative
-- cachix push gi-gtk-declarative --watch-store&
-- |
-  if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
-     cachix push gi-gtk-declarative --watch-store&
-     nix-build -j2 -A gi-gtk-declarative -A gi-gtk-declarative-app-simple -A examples \
-      | cachix push gi-gtk-declarative
-  else
-     nix-build -j2 -A gi-gtk-declarative -A gi-gtk-declarative-app-simple -A examples
-  fi
+  # test that source-distributions can be generated
+  - cabal new-sdist all
+  - mv dist-newstyle/sdist/*.tar.gz ${DISTDIR}/
+  - cd ${DISTDIR} || false
+  - find . -maxdepth 1 -name '*.tar.gz' -exec tar -xvf '{}' \;
+  - "printf 'packages: gi-gtk-declarative-*/*.cabal gi-gtk-declarative-app-simple-*/*.cabal examples-*/*.cabal\\n' > cabal.project"
+  - "printf 'write-ghc-environment-files: always\\n' >> cabal.project"
+  - touch cabal.project.local
+  - "if ! $NOINSTALLEDCONSTRAINTS; then for pkg in $($HCPKG list --simple-output); do echo $pkg  | grep -vw -- gi-gtk-declarative | grep -vw -- gi-gtk-declarative-app-simple | grep -vw -- examples | sed 's/^/constraints: /' | sed 's/-[^-]*$/ installed/' >> cabal.project.local; done; fi"
+  - cat cabal.project || true
+  - cat cabal.project.local || true
+  # this builds all libraries and executables (without tests/benchmarks)
+  - cabal new-build -w ${HC} --disable-tests --disable-benchmarks all
+
+  # build & run tests, build benchmarks
+  - cabal new-build -w ${HC} ${TEST} ${BENCH} all
+
+  # cabal check
+  - (cd gi-gtk-declarative-* && cabal check)
+  - (cd gi-gtk-declarative-app-simple-* && cabal check)
+  - (cd examples-* && cabal check)
+
+  # haddock
+  - if $HADDOCK; then cabal new-haddock -w ${HC} ${TEST} ${BENCH} all; else echo "Skipping haddock generation";fi
+
+  # Build without installed constraints for packages in global-db
+  - if $UNCONSTRAINED; then rm -f cabal.project.local; echo cabal new-build -w ${HC} --disable-tests --disable-benchmarks all; else echo "Not building without installed constraints"; fi
+
+# REGENDATA ["cabal.project"]
+# EOF
